Repository dotnet/docs.de-de, pull requests merged in 2019-10, with the labels that each got.

#153 Fix German MT for error messages
  docs/framework/winforms/controls/design-time-errors-in-the-windows-forms-designer.md
Labels: Accepted, Technical Issue

#158 Revision of german grammar for get-started-with-visual-studio-for-mac.md
  docs/fsharp/get-started/get-started-with-visual-studio-for-mac.md
Labels: Linguistic Suggestion, Partially Accepted

#155 Revision of german grammar for index.md
  docs/fsharp/get-started/index.md
Labels: Accepted, Linguistic Suggestion

#156 Revision of german grammar for what-is-fsharp.md
  docs/fsharp/what-is-fsharp.md
Labels: Accepted, Linguistic Suggestion

#157 Revision of german grammar for get-started-visual-studio.md
  docs/fsharp/get-started/get-started-visual-studio.md
Labels: Accepted, Linguistic Suggestion
